#! /bin/sh

# Mount ftp
#curlftpfs ftp://... /home/osboxes/...

# for TigerVNC Server
#unset SESSION_MANAGER
#unset DBUS_SESSION_BUS_ADDRESS

# X-screen Saver off
xset -dpms
xset s off
xset s noblank

# Environments
export TERMINAL=/usr/bin/alacritty
export QT_QPA_PLATFORMTHEME=gtk2
export XDG_SESSION_TYPE=x11

# ElmerFEM
export ELMER_HOME=$HOME/git/elmerfem/install/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ELMER_HOME/lib
export PATH=$PATH:$ELMER_HOME/bin

# Start
xrdb -merge ~/.Xresources
exec i3
